name = "adultdvdempire-api"
main = "index.js" # Entry point for your Worker
compatibility_date = "2024-01-01"

[env.production]
# Add environment variables here if needed
NODE_ENV = "production"

# Optional: If you want to deploy to a specific zone
# zone_id = "your-zone-id"